; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# Specify the port to upload/flash the ESP32
upload_port = /dev/ttyUSB0

# Specify the port to read Serial.print() logs
monitor_port = /dev/ttyUSB0


lib_deps =
    # micro-ROS library for ROS 2 Humble
    https://github.com/micro-ROS/micro_ros_arduino.git#v2.0.8-humble
    
    # Wollewald MPU9250 library (which also supports basic MPU6050 operations)
    https://github.com/wollewald/MPU9250_WE.git
    
    # Built-in Wire library for I2C communication
    Wire

build_flags =
    # 1. Point the linker to the directory containing ESP32's precompiled libmicroros.a
    -L ./.pio/libdeps/esp32dev/micro_ros_arduino/src/esp32/
    
    # 2. Tell the linker to link against libmicroros.a
    -lmicroros
    
    # 3. Define the ESP32 platform flag
    -D ESP32